from enum import Enum

class MonthlyUpdateCols(str, Enum):
    ELECTOR_NUMBER = "ElectorNumber"
    ELECTOR_DOB = "ElectorDOB"
    ELECTOR_SURNAME = "ElectorSurname"
    ELECTOR_FORENAME = "ElectorForename"
    MARKERS = "MarkersRegisterText"
    ADDRESS_1 = "PropertyAddress1"
    ADDRESS_2 = "PropertyAddress2"
    ADDRESS_3 = "PropertyAddress3"
    ADDRESS_4 = "PropertyAddress4"
    ADDRESS_5 = "PropertyAddress5"
    POSTCODE = "PropertyPostCode"

class FullRegisterCols(str, Enum):
    ELECTOR_ID = "Elector ID"
    PREFIX = "Elector Number Prefix"
    NUMBER = "Elector Number"
    SUFFIX = "Elector Number Suffix"
    MARKERS = "Elector Markers"
    DOB = "Elector DOB"
    SURNAME = "Elector Surname"
    FORENAME = "Elector Forename"
    ADDRESS_1 = "Address1"
    ADDRESS_2 = "Address2"
    ADDRESS_3 = "Address3"
    ADDRESS_4 = "Address4"
    ADDRESS_5 = "Address5"
    ADDRESS_6 = "Address6"
    POSTCODE = "PostCode"

class TVVUploadCols(str, Enum):
    FORENAME = "Forename"
    MIDDLE_NAMES = "Middle Names"
    SURNAME = "Surname"
    DATE_OF_ATTAINMENT = "Date of Attainment"
    UPRN = "UPRN"
    ADDRESS_1 = "Address1"
    ADDRESS_2 = "Address2"
    ADDRESS_3 = "Address3"
    ADDRESS_4 = "Address4"
    ADDRESS_5 = "Address5"
    ADDRESS_6 = "Address6"
    POSTCODE = "PostCode"
    PREFIX = "Elector Number Prefix"
    NUMBER = "Elector Number"
    SUFFIX = "Elector Number Suffix"
